[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
   YARN_VERSION = "4.2.2"
   YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"

[build]
command = "yarn nx build tangle-dapp --verbose --skip-nx-cache"
publish = "./dist/apps/tangle-dapp/.next"
