name: Auto Sync Master with Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  sync-branches:
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Develop
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout Master and Fast-Forward Merge
        run: |
          git checkout develop
          git fetch origin
          git checkout master
          git pull
          git merge --ff-only origin/develop

      - name: Push Changes to Master
        run: git push origin master --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
